#!/usr/bin/env python3
"""
Simple generator: plan -> validate -> apply (or PR).
Usage:
  export REPOWRITER_BASE_URL="http://localhost:7071"
  python3 tools/illuvrse_generator.py --task "Add GET /api/hello" --acceptance 'GET /api/hello returns 200 JSON {"msg":"hello"}' --allowed "RepoWriter/server/,src/services/" --apply
"""
import os, sys, json, argparse, requests, time

REPOWRITER = os.environ.get("REPOWRITER_BASE_URL", "http://localhost:7071")
TIMEOUT = 300

def plan_task(task, acceptance, allowed):
    prompt = {
        "prompt": f"{task}\n\nAcceptance: {acceptance}\nAllowed paths: {allowed}\nReturn EXACT JSON: {{steps:[{{explanation:string,patches:[{{path,content?,diff?}}]}}]}}",
        "memory": []
    }
    r = requests.post(f"{REPOWRITER}/api/openai/plan", json=prompt, timeout=TIMEOUT)
    r.raise_for_status()
    return r.json()

def extract_patches(plan):
    patches = []
    for s in plan.get("plan", {}).get("steps", []):
        patches += s.get("patches", [])
    return patches

def validate_patches(patches):
    r = requests.post(f"{REPOWRITER}/api/openai/validate", json={"patches": patches}, timeout=600)
    r.raise_for_status()
    return r.json()

def apply_patches(patches):
    r = requests.post(f"{REPOWRITER}/api/openai/apply", json={"patches": patches, "mode": "apply"}, timeout=600)
    r.raise_for_status()
    return r.json()

def create_pr(patches, branch, title, body):
    payload = {"branchName": branch, "patches": patches, "commitMessage": title, "prTitle": title, "prBody": body}
    r = requests.post(f"{REPOWRITER}/api/repo/pr", json=payload, timeout=600)
    r.raise_for_status()
    return r.json()

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--task", required=True)
    ap.add_argument("--acceptance", required=True)
    ap.add_argument("--allowed", default="RepoWriter/server/,src/")
    ap.add_argument("--apply", action="store_true", help="apply locally (commit)")
    ap.add_argument("--branch", default=f"repowriter/task-{int(time.time())}")
    args = ap.parse_args()

    print("Planning:", args.task)
    plan = plan_task(args.task, args.acceptance, args.allowed)
    patches = extract_patches(plan)
    if not patches:
        print("No patches produced; aborting.")
        print(json.dumps(plan, indent=2)[:2000])
        sys.exit(1)

    print(f"Got {len(patches)} patches → validating...")
    val = validate_patches(patches)
    if not val.get("ok") or not val.get("result",{}).get("ok"):
        print("Validation failed. Output:")
        print(json.dumps(val, indent=2)[:4000])
        sys.exit(1)
    print("Validation OK.")

    if args.apply:
        res = apply_patches(patches)
        print("Apply result:", json.dumps(res, indent=2))
    else:
        print("Creating PR:", args.branch)
        pr = create_pr(patches, args.branch, args.task, f"Generated by RepoWriter: {args.task}")
        print("PR:", json.dumps(pr, indent=2))

if __name__ == "__main__":
    main()

